In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pylab as plt

In [2]:
dataset = tf.keras.datasets.boston_housing

(train_data, train_label), (test_data, test_label) = dataset.load_data()

57344/57026 [==============================] - 0s 1us/step


In [18]:
train_data.shape

(404, 13)

In [15]:
test_data.shape

(102, 13)

In [22]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(train_data.shape[1],)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)
])

In [23]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 64)                896       
_________________________________________________________________
dense_13 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_14 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 33        
Total params: 13,377
Trainable params: 13,377
Non-trainable params: 0
_________________________________________________________________


In [39]:
mean = train_data.mean(axis=0)
train_data = train_data-mean
std = train_data.std(axis=0)
train_data = train_data/std


In [63]:
mean, std

(array([3.74511057e+00, 1.14801980e+01, 1.11044307e+01, 6.18811881e-02,
        5.57355941e-01, 6.26708168e+00, 6.90106436e+01, 3.74027079e+00,
        9.44059406e+00, 4.05898515e+02, 1.84759901e+01, 3.54783168e+02,
        1.27408168e+01]),
 array([9.22929073e+00, 2.37382770e+01, 6.80287253e+00, 2.40939633e-01,
        1.17147847e-01, 7.08908627e-01, 2.79060634e+01, 2.02770050e+00,
        8.68758849e+00, 1.66168506e+02, 2.19765689e+00, 9.39946015e+01,
        7.24556085e+00]))

In [42]:
test_data -= mean
test_data /= std

In [43]:
model.compile(optimizer="rmsprop", loss="mse", metrics=['mae'])        #mean squeare entropy, mean absolut error

In [44]:
history = model.fit(train_data, train_label, batch_size=16, epochs=10, verbose=0)

In [46]:
model.evaluate(test_data, test_label)

102/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[24.174612606272976, 3.422252]

In [55]:
prediction = model.predict(test_data)

In [66]:
n=0
prediction[n]

array([7.5206647], dtype=float32)

In [67]:
test_label[n]

7.2